-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)

-- 1. Profiles (extends auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  avatar_url text,
  learning_goal text check (learning_goal in ('travel', 'culture', 'business', 'family')),
  learning_level text check (learning_level in ('beginner', 'intermediate', 'advanced')),
  onboarded boolean default false,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data ->> 'name',
    new.email,
    new.raw_user_meta_data ->> 'picture'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2. User learned words
create table if not exists public.user_learned_words (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  word_id integer not null,
  learned_at timestamptz default now(),
  unique(user_id, word_id)
);

alter table public.user_learned_words enable row level security;

create policy "Users can read own learned words"
  on public.user_learned_words for select
  using (auth.uid() = user_id);

create policy "Users can insert own learned words"
  on public.user_learned_words for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own learned words"
  on public.user_learned_words for delete
  using (auth.uid() = user_id);

-- 3. User streaks
create table if not exists public.user_streaks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade unique not null,
  current_streak integer default 0,
  longest_streak integer default 0,
  last_activity_date date default current_date
);

alter table public.user_streaks enable row level security;

create policy "Users can read own streak"
  on public.user_streaks for select
  using (auth.uid() = user_id);

create policy "Users can upsert own streak"
  on public.user_streaks for insert
  with check (auth.uid() = user_id);

create policy "Users can update own streak"
  on public.user_streaks for update
  using (auth.uid() = user_id);

-- 4. User XP
create table if not exists public.user_xp (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  xp_amount integer not null,
  source text check (source in ('lesson', 'quiz', 'journal', 'streak', 'echo_practice')),
  created_at timestamptz default now()
);

alter table public.user_xp enable row level security;

create policy "Users can read own XP"
  on public.user_xp for select
  using (auth.uid() = user_id);

create policy "Users can insert own XP"
  on public.user_xp for insert
  with check (auth.uid() = user_id);

-- 5. Journal entries
create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  prompt_nepali text,
  prompt_roman text,
  prompt_english text,
  response_text text not null,
  created_at timestamptz default now()
);

alter table public.journal_entries enable row level security;

create policy "Users can read own journal entries"
  on public.journal_entries for select
  using (auth.uid() = user_id);

create policy "Users can insert own journal entries"
  on public.journal_entries for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own journal entries"
  on public.journal_entries for delete
  using (auth.uid() = user_id);

-- 6. AI chat history
create table if not exists public.ai_chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

alter table public.ai_chat_history enable row level security;

create policy "Users can read own chat history"
  on public.ai_chat_history for select
  using (auth.uid() = user_id);

create policy "Users can insert own chat messages"
  on public.ai_chat_history for insert
  with check (auth.uid() = user_id);

-- 7. RPC: get total XP for a user
create or replace function public.get_total_xp(p_user_id uuid)
returns integer
language sql stable
as $$
  select coalesce(sum(xp_amount), 0)::integer
  from public.user_xp
  where user_id = p_user_id;
$$;
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)
-- Migration 002: widen XP source CHECK + spaced-repetition table

-- 1. Widen user_xp.source CHECK constraint
--    Old constraint only allowed ('lesson','quiz','journal','streak','echo_practice')
--    which rejected 'ai_tutor' inserts (bug: queued ops retried forever).
alter table public.user_xp drop constraint if exists user_xp_source_check;

alter table public.user_xp add constraint user_xp_source_check
  check (source in (
    'lesson',
    'quiz',
    'journal',
    'streak',
    'echo_practice',
    'ai_tutor',
    'review',
    'mistakes',
    'sentence',
    'listening',
    'grammar'
  ));

-- 2. Spaced repetition state per word (Leitner boxes 1-5)
create table if not exists public.user_word_srs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  word_id integer not null,
  box integer not null default 1 check (box between 1 and 5),
  last_result boolean,
  last_reviewed_at timestamptz,
  due_at timestamptz,
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  unique(user_id, word_id)
);

alter table public.user_word_srs enable row level security;

create policy "Users can read own srs"
  on public.user_word_srs for select
  using (auth.uid() = user_id);

create policy "Users can insert own srs"
  on public.user_word_srs for insert
  with check (auth.uid() = user_id);

create policy "Users can update own srs"
  on public.user_word_srs for update
  using (auth.uid() = user_id);

create policy "Users can delete own srs"
  on public.user_word_srs for delete
  using (auth.uid() = user_id);
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)
-- Migration 003: heatmap RPC, journal AI feedback, streak freeze, weekly leaderboard

-- 1. RPC: daily XP totals for heatmap (security invoker; RLS already limits to own rows,
--    but filter by p_user_id explicitly anyway)
create or replace function public.get_daily_xp(p_user_id uuid)
returns table(day date, xp integer)
language sql stable
as $$
  select created_at::date as day, coalesce(sum(xp_amount), 0)::integer as xp
  from public.user_xp
  where user_id = p_user_id
  group by created_at::date
  order by day;
$$;

-- 2. Journal AI feedback
alter table public.journal_entries
  add column if not exists feedback_text text;

-- 3. Streak freeze (ISO week string, e.g. '2026-W28', when freeze was consumed)
alter table public.user_streaks
  add column if not exists freeze_week text;

-- 4. RPC: weekly leaderboard.
--    SECURITY DEFINER because RLS blocks cross-user reads of user_xp/profiles.
--    Returns only non-sensitive fields.
create or replace function public.get_weekly_leaderboard(p_limit integer default 50)
returns table(name text, avatar_url text, weekly_xp integer, rank bigint)
language sql stable
security definer
set search_path = public
as $$
  select
    coalesce(p.name, 'Learner') as name,
    p.avatar_url,
    sum(x.xp_amount)::integer as weekly_xp,
    rank() over (order by sum(x.xp_amount) desc) as rank
  from public.user_xp x
  join public.profiles p on p.id = x.user_id
  where x.created_at >= date_trunc('week', now())
  group by p.id, p.name, p.avatar_url
  order by weekly_xp desc
  limit greatest(1, least(p_limit, 100));
$$;

revoke all on function public.get_weekly_leaderboard(integer) from public;
revoke all on function public.get_weekly_leaderboard(integer) from anon;
grant execute on function public.get_weekly_leaderboard(integer) to authenticated;
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)
-- Migration 004: multi-conversation AI chat (Aama)

-- 1. Conversations table
create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  title text not null default 'New chat',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.ai_conversations enable row level security;

drop policy if exists "Users can read own conversations" on public.ai_conversations;
create policy "Users can read own conversations"
  on public.ai_conversations for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own conversations" on public.ai_conversations;
create policy "Users can insert own conversations"
  on public.ai_conversations for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own conversations" on public.ai_conversations;
create policy "Users can update own conversations"
  on public.ai_conversations for update
  using (auth.uid() = user_id);

drop policy if exists "Users can delete own conversations" on public.ai_conversations;
create policy "Users can delete own conversations"
  on public.ai_conversations for delete
  using (auth.uid() = user_id);

-- 2. Link chat history rows to a conversation (nullable, backward compat)
alter table public.ai_chat_history
  add column if not exists conversation_id uuid references public.ai_conversations(id) on delete cascade;

-- 3. Missing delete policy on ai_chat_history (only had select/insert before)
drop policy if exists "Users can delete own chat messages" on public.ai_chat_history;
create policy "Users can delete own chat messages"
  on public.ai_chat_history for delete
  using (auth.uid() = user_id);

-- 4. Backfill: one 'Legacy chat' conversation per user with pre-existing null-conversation rows.
--    Idempotent: only touches rows that are still unassigned.
do $$
declare
  r record;
  new_conv_id uuid;
begin
  for r in
    select distinct user_id
    from public.ai_chat_history
    where conversation_id is null
  loop
    insert into public.ai_conversations (user_id, title)
    values (r.user_id, 'Legacy chat')
    returning id into new_conv_id;

    update public.ai_chat_history
    set conversation_id = new_conv_id
    where user_id = r.user_id
      and conversation_id is null;
  end loop;
end $$;

-- 5. Indexes
create index if not exists ai_chat_history_conversation_id_idx
  on public.ai_chat_history (conversation_id);

create index if not exists ai_conversations_user_id_updated_at_idx
  on public.ai_conversations (user_id, updated_at desc);
-- Run this in Supabase SQL Editor to fix RLS policies
-- Dashboard → SQL Editor → New Query → Paste → Run

-- profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
DROP POLICY IF EXISTS "Users can read own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can read own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- user_xp
ALTER TABLE user_xp ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own xp" ON user_xp;
DROP POLICY IF EXISTS "Users can read own xp" ON user_xp;
CREATE POLICY "Users can insert own xp" ON user_xp FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can read own xp" ON user_xp FOR SELECT USING (auth.uid() = user_id);

-- user_streaks
ALTER TABLE user_streaks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own streak" ON user_streaks;
DROP POLICY IF EXISTS "Users can read own streak" ON user_streaks;
DROP POLICY IF EXISTS "Users can update own streak" ON user_streaks;
CREATE POLICY "Users can insert own streak" ON user_streaks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can read own streak" ON user_streaks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own streak" ON user_streaks FOR UPDATE USING (auth.uid() = user_id);

-- user_learned_words
ALTER TABLE user_learned_words ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own words" ON user_learned_words;
DROP POLICY IF EXISTS "Users can read own words" ON user_learned_words;
DROP POLICY IF EXISTS "Users can delete own words" ON user_learned_words;
CREATE POLICY "Users can insert own words" ON user_learned_words FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can read own words" ON user_learned_words FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own words" ON user_learned_words FOR DELETE USING (auth.uid() = user_id);

-- journal_entries
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can insert own journal" ON journal_entries;
DROP POLICY IF EXISTS "Users can read own journal" ON journal_entries;
CREATE POLICY "Users can insert own journal" ON journal_entries FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can read own journal" ON journal_entries FOR SELECT USING (auth.uid() = user_id);

-- get_total_xp RPC function (if not already created)
CREATE OR REPLACE FUNCTION get_total_xp(p_user_id UUID)
RETURNS INTEGER AS $$
  SELECT COALESCE(SUM(xp_amount), 0)::INTEGER FROM user_xp WHERE user_id = p_user_id;
$$ LANGUAGE SQL SECURITY DEFINER;
