-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)

-- 1. Profiles (extends auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  avatar_url text,
  learning_goal text check (learning_goal in ('travel', 'culture', 'business', 'family')),
  learning_level text check (learning_level in ('beginner', 'intermediate', 'advanced')),
  onboarded boolean default false,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data ->> 'name',
    new.email,
    new.raw_user_meta_data ->> 'picture'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2. User learned words
create table if not exists public.user_learned_words (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  word_id integer not null,
  learned_at timestamptz default now(),
  unique(user_id, word_id)
);

alter table public.user_learned_words enable row level security;

create policy "Users can read own learned words"
  on public.user_learned_words for select
  using (auth.uid() = user_id);

create policy "Users can insert own learned words"
  on public.user_learned_words for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own learned words"
  on public.user_learned_words for delete
  using (auth.uid() = user_id);

-- 3. User streaks
create table if not exists public.user_streaks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade unique not null,
  current_streak integer default 0,
  longest_streak integer default 0,
  last_activity_date date default current_date
);

alter table public.user_streaks enable row level security;

create policy "Users can read own streak"
  on public.user_streaks for select
  using (auth.uid() = user_id);

create policy "Users can upsert own streak"
  on public.user_streaks for insert
  with check (auth.uid() = user_id);

create policy "Users can update own streak"
  on public.user_streaks for update
  using (auth.uid() = user_id);

-- 4. User XP
create table if not exists public.user_xp (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  xp_amount integer not null,
  source text check (source in ('lesson', 'quiz', 'journal', 'streak', 'echo_practice')),
  created_at timestamptz default now()
);

alter table public.user_xp enable row level security;

create policy "Users can read own XP"
  on public.user_xp for select
  using (auth.uid() = user_id);

create policy "Users can insert own XP"
  on public.user_xp for insert
  with check (auth.uid() = user_id);

-- 5. Journal entries
create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  prompt_nepali text,
  prompt_roman text,
  prompt_english text,
  response_text text not null,
  created_at timestamptz default now()
);

alter table public.journal_entries enable row level security;

create policy "Users can read own journal entries"
  on public.journal_entries for select
  using (auth.uid() = user_id);

create policy "Users can insert own journal entries"
  on public.journal_entries for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own journal entries"
  on public.journal_entries for delete
  using (auth.uid() = user_id);

-- 6. AI chat history
create table if not exists public.ai_chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

alter table public.ai_chat_history enable row level security;

create policy "Users can read own chat history"
  on public.ai_chat_history for select
  using (auth.uid() = user_id);

create policy "Users can insert own chat messages"
  on public.ai_chat_history for insert
  with check (auth.uid() = user_id);

-- 7. RPC: get total XP for a user
create or replace function public.get_total_xp(p_user_id uuid)
returns integer
language sql stable
as $$
  select coalesce(sum(xp_amount), 0)::integer
  from public.user_xp
  where user_id = p_user_id;
$$;
