-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)
-- Migration 002: widen XP source CHECK + spaced-repetition table

-- 1. Widen user_xp.source CHECK constraint
--    Old constraint only allowed ('lesson','quiz','journal','streak','echo_practice')
--    which rejected 'ai_tutor' inserts (bug: queued ops retried forever).
alter table public.user_xp drop constraint if exists user_xp_source_check;

alter table public.user_xp add constraint user_xp_source_check
  check (source in (
    'lesson',
    'quiz',
    'journal',
    'streak',
    'echo_practice',
    'ai_tutor',
    'review',
    'mistakes',
    'sentence',
    'listening',
    'grammar'
  ));

-- 2. Spaced repetition state per word (Leitner boxes 1-5)
create table if not exists public.user_word_srs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  word_id integer not null,
  box integer not null default 1 check (box between 1 and 5),
  last_result boolean,
  last_reviewed_at timestamptz,
  due_at timestamptz,
  correct_count integer not null default 0,
  incorrect_count integer not null default 0,
  unique(user_id, word_id)
);

alter table public.user_word_srs enable row level security;

create policy "Users can read own srs"
  on public.user_word_srs for select
  using (auth.uid() = user_id);

create policy "Users can insert own srs"
  on public.user_word_srs for insert
  with check (auth.uid() = user_id);

create policy "Users can update own srs"
  on public.user_word_srs for update
  using (auth.uid() = user_id);

create policy "Users can delete own srs"
  on public.user_word_srs for delete
  using (auth.uid() = user_id);
